[package]
name = "rust_socket"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.4", features = ["derive"] }
pcap-file = "2.0.0"
pnet ="0.34.0"
rm = "0.3.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
socket2 = "0.6.1"
